### ISSUE TITLE
How is this supposed to work?

### ISSUE THREAD

**Issue by scottwojan** [pubnub/transportation#1]
I'm trying to get this to work but there is no setup or configuration instructions.  can someone please help?

**Comment by scottwojan** [comment]
This project is bullshit marketing fluff.  There is no real meat to this AT ALL!!!!!!!!!!!

**Comment by drnugent** [comment]
Hi Scott, this is a 101-style introduction to the different ways to build connected car applications using PubNub. It's intended to be a jumping-off point for you to incorporate your own business logic and build a prototype. What is your application?

**Comment by scottwojan** [comment]
This is labelled “CONNECTED CAR SOLUTION KIT” which would make the reader believe this is actually a well thought out solution/SDK where in reality it’s nothing more than showing the use of channels.  To label this a solution kit is laughable.  This doesn’t even scratch the surface for the needs to do a transportation app.

**Comment by drnugent** [comment]
Hi Scott, if you'd like to tell me more about your project, I'd be happy to describe some best practices our connected car customers use. Since each connected car application is customized (e.g. dispatching is handled differently by each vendor) this kit leaves those callbacks open to the implementer. Feel free to reach out to me at dave@pubnub.com to discuss your particular solution. Good luck with your connected car project!
